/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesIndustryRouteImport } from './routes/industries.$industry'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndustryRoute = IndustriesIndustryRouteImport.update({
  id: '/$industry',
  path: '/$industry',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/locations': typeof LocationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/$industry': typeof IndustriesIndustryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/industries'
    | '/locations'
    | '/sitemap.xml'
    | '/industries/$industry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/industries'
    | '/locations'
    | '/sitemap.xml'
    | '/industries/$industry'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/industries'
    | '/locations'
    | '/sitemap.xml'
    | '/industries/$industry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$industry': {
      id: '/industries/$industry'
      path: '/$industry'
      fullPath: '/industries/$industry'
      preLoaderRoute: typeof IndustriesIndustryRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesIndustryRoute: typeof IndustriesIndustryRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesIndustryRoute: IndustriesIndustryRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  LocationsRoute: LocationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
